# Generated by Django 4.2.26 on 2025-12-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
